### ISSUE TITLE
global.ini

### ISSUE THREAD

**Issue by SilverHawk2020** [yn-sun/cnn-ga#2]
Could you please provide an example of a working configuration file "global.ini" to test the code with it? 
I keep getting endless errors of NoSectionError and NoOptionError
Providing a working file to start with it would be greatly helpful.

Thank you so much in advance

**Comment by MrZilinXiao** [comment]
It's strange since my local environment raises no errors when parsing global.ini.
Would you like to provide a detailed example traceback for us to determine where the problem lies?

**Comment by MrZilinXiao** [comment]
> Could you please provide an example of a working configuration file "global.ini" to test the code with it?
> I keep getting endless errors of NoSectionError and NoOptionError
> Providing a working file to start with it would be greatly helpful.
> 
> Thank you so much in advance

I may have some clues about your errors: since former utils.py is not for cnn-ga, you can try out the latest utils.py to avoid such exceptions.

**Comment by SilverHawk2020** [comment]
You are correct, the weird exceptions were a result of the wrong utils.py file, that made it search for the wrong options in global.ini.
I'll close the issue.
Thank you so much
