### ISSUE TITLE
ImportError: cannot import name 'DenseUnit' from 'genetic.population'

### ISSUE THREAD

**Issue by SilverHawk2020** [yn-sun/cnn-ga#3]
utils.py imports DenseUnit from genetic.population, and it doesn't exist there, so I get this error:

  File "utils.py", line 5, in <module>
    from genetic.population import Population, Individual, DenseUnit, ResUnit, PoolUnit

ImportError: cannot import name 'DenseUnit' from 'genetic.population'

**Comment by yn-sun** [comment]
Hi Silver, I will add the files soon and let you know then. Meanwhile, you could check the codes from "https://github.com/yn-sun/ea-cnn" which has the very similar files for this project.

**Comment by SilverHawk2020** [comment]
Thank you so much for the quick response, the link of the other paper is very useful. However, the code here seems to be mixed with the other one, i.e. many parts seem to be dependent on blocks defined in the other paper, but they shouldn't be defined in this one.
I'll be waiting for the working version of this paper's code, and thank you for providing us with your great work :)

**Comment by MrZilinXiao** [comment]
> Thank you so much for the quick response, the link of the other paper is very useful. However, the code here seems to be mixed with the other one, i.e. many parts seem to be dependent on blocks defined in the other paper, but they shouldn't be defined in this one.
> I'll be waiting for the working version of this paper's code, and thank you for providing us with your great work :)

Sorry for the inconvenience, I was the one who helped Prof. Sun to arrange&upload utils.py on Github, and I confuse it with the one in ea-cnn.
A pull request has been made. Before it is merged into the master branch,  you may refer to here: https://github.com/yn-sun/cnn-ga/pull/4

**Comment by SilverHawk2020** [comment]
Thank you for providing the correct utils.py file, I'll use it instead of the wrong file.
I'll close the issue

**Comment by QAQureshi** [comment]
Hi, will you please tell me the version number of PyTorch you used to execute this code?

**Comment by SilverHawk2020** [comment]
> Hi, will you please tell me the version number of PyTorch you used to execute this code?

Hi,
I've executed it with torch version 1.6.0 without a problem.

**Comment by yn-sun** [comment]
It has been updated to the up-to-date PyTorch version. Please check it!

Sent from my iPhone

On Apr 25, 2022, at 15:29, SilverHawk2020 ***@***.***> wrote:

﻿

Hi, will you please tell me the version number of PyTorch you used to execute this code?

Hi,
I've executed it with torch version 1.6.0 without a problem.

**Comment by yn-sun** [comment]
It has been updated to up-to-date PyTorch version!

Sent from my iPhone

On Apr 25, 2022, at 13:13, QAQureshi ***@***.***> wrote:

﻿

Hi, will you please tell me the version number of PyTorch you used to execute this code?
